version: "3.9"
services:
  kong:
    image: kong:3.1.1
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
    ports:
      - "8000:8000"
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
      - ./logs:/tmp
  web:
    build: 
      context: .
      dockerfile: Dockerfile-python
    container_name: web
    ports:
      - "5000"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "33000:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
      interval: 10s


  
   