version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-python
    container_name: web
    ports:
      - "8000:5000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build: 
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "33000:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 3


  
   